-- =====================================================
-- Table: matches
-- Purpose: Control table for ETL orchestration
-- =====================================================

CREATE TABLE matches (
    id              NUMBER
                        GENERATED BY DEFAULT AS IDENTITY
                        PRIMARY KEY,

    match_date      DATE
                        DEFAULT TRUNC(SYSDATE)
                        NOT NULL,

    title           VARCHAR2(150)
                        NOT NULL,

    sofascore_link  VARCHAR2(150)
                        NOT NULL,

    fbref_link      VARCHAR2(150)
                        NOT NULL,

    etl_status      VARCHAR2(20)
                        DEFAULT 'PENDING'
                        NOT NULL,

    last_modified   DATE
                        DEFAULT SYSDATE
                        NOT NULL
);

-- Index for ETL filtering
CREATE INDEX idx_matches_status
ON matches (etl_status);

-- Index for searching by date and title (prefix searches)
CREATE INDEX idx_matches_date
ON matches (match_date);

-- Optional: Full-text index for advanced LIKE searches
CREATE INDEX idx_matches_title_text
ON matches(title)
INDEXTYPE IS CTXSYS.CONTEXT;




